export enum AuditAction {
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  USER_DELETED = 'USER_DELETED',
  USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
  SUBSCRIPTION_OVERRIDE = 'SUBSCRIPTION_OVERRIDE',
  CONTENT_REPORT_RESOLVED = 'CONTENT_REPORT_RESOLVED',
  CONTENT_REPORT_DISMISSED = 'CONTENT_REPORT_DISMISSED',
  POST_SOFT_DELETED = 'POST_SOFT_DELETED',
  POST_RESTORED = 'POST_RESTORED',
}
